#!/bin/sh

EPOS=
APP=$EPOS/app
IMG=$EPOS/img
APPLICATIONS="hello producer_consumer philosophers_dinner"
MODES="LIBRARY KERNEL"
N_TARGETS=4
TARGETS=("IA32 PC Legacy_PC" "RV32 RISCV SiFive_E" "ARMv7 Cortex LM3S811" "ARMv7 Cortex Raspberry_Pi3")
LIBRARY_TESTS="alarm_test"
KERNEL_TESTS="alarm_test task_test"

set -e

cd $EPOS

for MODE in $MODES ; do
    eval TESTS=\$$"$MODE""_TESTS"
    printf "\n********************************************************************************\n"
    printf "\nPreparing test set for mode $MODE: $APPLICATIONS $TESTS\n\n"
    make linktest
    for ((i = 0; i < N_TARGETS; i++)) do
        set -- ${TARGETS[$i]}
        ARCH=$1
        MACH=$2
        MMOD=$3
        for TEST in $APPLICATIONS $TESTS ; do
            sed -e "s/^\(.*MODE = \).*;$/\1$MODE;/" -e "s/^\(.*ARCHITECTURE = \).*;$/\1$ARCH;/" -e "s/^\(.*MACHINE = \).*;$/\1$MACH;/" $APP/$TEST/$TEST""_traits.h -e "s/^\(.*MODEL = \).*;$/\1$MMOD;/" -i $APP/$TEST/$TEST""_traits.h
        done
        printf "\n--------------------------------------------------------------------------------\n"
        printf "Running test set for $MMOD (a $MACH on $ARCH) in mode $MODE\n\n"
        make "TESTS=$TESTS" gittest
        for TEST in $APPLICATIONS $TESTS ; do
            mv -n $IMG/$TEST     $IMG/$MODE"-"$ARCH"_"$MACH"_"$MMOD"_"$TEST &> /dev/null
            mv -n $IMG/$TEST.img $IMG/$MODE"-"$ARCH"_"$MACH"_"$MMOD"_"$TEST".img" &> /dev/null
            mv -n $IMG/$TEST.out $IMG/$MODE"-"$ARCH"_"$MACH"_"$MMOD"_"$TEST".out" &> /dev/null        
        done
    done
done
